Repository CovEducation/CovEducation, pull requests merged in 2020-07, with the labels that each got.

#17 Added Tabs Functionality
  .idea/.gitignore
  .idea/coved v2.iml
  .idea/dictionaries/ojasw.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  package.json
  packages/client/package-lock.json
  packages/client/package.json
  packages/client/src/App.js
  packages/client/src/components/Tabs/extra.js
  packages/client/src/components/Tabs/index.js
  packages/client/src/components/TextBox/index.js
Labels: enhancement

#13 Basic Textbox Functionality
  .idea/.gitignore
  .idea/coved v2.iml
  .idea/dictionaries/ojasw.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  package-lock.json
  package.json
  packages/client/package-lock.json
  packages/client/package.json
  packages/client/src/App.js
  packages/client/src/components/Dropdown/global.js
  packages/client/src/components/Dropdown/index.js
  packages/client/src/components/Dropdown/index.scss
  packages/client/src/components/Tabs/index.js
  packages/client/src/components/TextBox/index.js
  packages/client/src/index.css
Labels: enhancement

#22 Add Accordion component
  packages/client/src/App.js
  packages/client/src/components/Accordion/index.js
  packages/client/src/components/Icons/ArrowDown.js
  packages/client/src/constants.js
Labels: enhancement

#23 Update README.md
  README.md
Labels: documentation

#29 Styling Tabs
  packages/client/.gitignore
  packages/client/src/App.js
  packages/client/src/components/Tabs/extra.js
  packages/client/src/components/Tabs/index.js
Labels: styling

#32 rename type to id
  packages/client/src/components/TextBox/index.js
Labels: invalid

#35 Move firebase config to .env files
  README.md
  packages/client/.env.development
  packages/client/src/providers/AuthProvider/index.js
Labels: documentation

#39 find-a-mentor filters
  packages/client/src/App.js
  packages/client/src/components/Accordion/index.js
  packages/client/src/components/Checkbox/index.js
  packages/client/src/components/Icons/ArrowDown.js
  packages/client/src/components/Icons/Checkmark.js
  packages/client/src/constants.js
  packages/client/src/pages/FindAMentor/Mentor.js
  packages/client/src/pages/FindAMentor/MentorFilters.js
  packages/client/src/pages/FindAMentor/MentorRequestFrame.js
  packages/client/src/pages/FindAMentor/index.js
  packages/client/src/utilities.js
Labels: enhancement

#36 Firebase Integration 🔥🔥🔥
  packages/client/package-lock.json
  packages/client/package.json
  packages/client/src/App.js
  packages/client/src/models/index.js
  packages/client/src/models/mentor.js
  packages/client/src/models/mentor.test.js
  packages/client/src/models/parent.js
  packages/client/src/models/parent.test.js
  packages/client/src/pages/SignIn/index.js
  packages/client/src/providers/AuthProvider/index.js
  packages/client/src/providers/AuthProvider/index.test.js
  packages/client/src/providers/FirebaseProvider/firebase.js
  packages/client/src/providers/FirebaseProvider/index.js
  packages/client/src/providers/FirebaseProvider/index.test.js
  packages/client/src/setupTests.js
Labels: on the way

#41 mentor cards to FindAMentor
  packages/client/public/stock-profile.png
  packages/client/src/pages/FindAMentor/Mentor.js
  packages/client/src/pages/FindAMentor/MentorCard.js
  packages/client/src/pages/FindAMentor/MentorGrid.js
  packages/client/src/pages/FindAMentor/MentorProfile.js
  packages/client/src/pages/FindAMentor/MentorRequestFrame.js
  packages/client/src/pages/FindAMentor/index.js
  packages/client/src/pages/Profile/index.js
  packages/client/src/utilities.js
Labels: enhancement

#42 Sign Up Wizard with state
  README.md
  package-lock.json
  packages/client/src/App.js
  packages/client/src/components/Button/index.js
  packages/client/src/components/Wizard/ProgressBar.js
  packages/client/src/constants.js
  packages/client/src/index.css
  packages/client/src/pages/SignUp/index.js
  packages/client/src/pages/SignUp/wizards/MentorWizard/forms/MentorStep1.js
  packages/client/src/pages/SignUp/wizards/MentorWizard/forms/MentorStep2.js
  packages/client/src/pages/SignUp/wizards/MentorWizard/forms/MentorStep3.js
  packages/client/src/pages/SignUp/wizards/MentorWizard/forms/MentorStep4.js
  packages/client/src/pages/SignUp/wizards/MentorWizard/index.js
  packages/client/src/pages/SignUp/wizards/ParentWizard/forms/ParentStep1.js
  packages/client/src/pages/SignUp/wizards/ParentWizard/forms/ParentStep2.js
  packages/client/src/pages/SignUp/wizards/ParentWizard/forms/ParentStep3.js
  packages/client/src/pages/SignUp/wizards/ParentWizard/forms/ParentStep4.js
  packages/client/src/pages/SignUp/wizards/ParentWizard/index.js
Labels: enhancement, help wanted, on the way
